<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>4&nbsp; Swaps – Financial Derivatives</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./week_05.html" rel="next">
<link href="./week_03.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./week_04.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Swaps</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./logo.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Financial Derivatives</a> 
        <div class="sidebar-tools-main">
    <div class="dropdown">
      <a href="" title="Download" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Download"><i class="bi bi-download"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./Financial-Derivatives.pdf">
              <i class="bi bi-file-pdf pe-1"></i>
            Download PDF
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./Financial-Derivatives.epub">
              <i class="bi bi-journal pe-1"></i>
            Download ePub
            </a>
          </li>
      </ul>
    </div>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-1" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-1">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
              <i class="bi bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
      </ul>
    </div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preamble</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week_01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction to Financial Derivatives</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week_02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Forwards and Futures</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week_03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Determination of Forward and Futures Prices</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week_04.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Swaps</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week_05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Options</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week_06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Options Trading Strategies and Hedging</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week_07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Reading Week</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week_08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Option Pricing - Binomial Trees</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week_09.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Option Pricing - Black-Scholes Model</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week_10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Options on Indices, Currencies, and Futures</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week_11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">The Greek Letters</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week_12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Structured Products I</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week_13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Structured Products II</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./time_value.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Time Value of Money</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./interest_rates.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Interest Rates</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#nature-of-swaps" id="toc-nature-of-swaps" class="nav-link active" data-scroll-target="#nature-of-swaps"><span class="header-section-number">4.1</span> Nature of Swaps</a></li>
  <li><a href="#interest-rate-swaps" id="toc-interest-rate-swaps" class="nav-link" data-scroll-target="#interest-rate-swaps"><span class="header-section-number">4.2</span> Interest Rate Swaps</a></li>
  <li><a href="#the-comparative-advantage-argument" id="toc-the-comparative-advantage-argument" class="nav-link" data-scroll-target="#the-comparative-advantage-argument"><span class="header-section-number">4.3</span> The Comparative-Advantage Argument</a></li>
  <li><a href="#valuation-of-interest-rate-swaps" id="toc-valuation-of-interest-rate-swaps" class="nav-link" data-scroll-target="#valuation-of-interest-rate-swaps"><span class="header-section-number">4.4</span> Valuation of Interest Rate Swaps</a></li>
  <li><a href="#currency-swaps" id="toc-currency-swaps" class="nav-link" data-scroll-target="#currency-swaps"><span class="header-section-number">4.5</span> Currency Swaps</a></li>
  <li><a href="#valuation-of-fixed-for-fixed-currency-swaps" id="toc-valuation-of-fixed-for-fixed-currency-swaps" class="nav-link" data-scroll-target="#valuation-of-fixed-for-fixed-currency-swaps"><span class="header-section-number">4.6</span> Valuation of Fixed-for-Fixed Currency Swaps</a></li>
  <li><a href="#other-currency-swaps" id="toc-other-currency-swaps" class="nav-link" data-scroll-target="#other-currency-swaps"><span class="header-section-number">4.7</span> Other Currency Swaps</a></li>
  <li><a href="#other-types-of-swaps" id="toc-other-types-of-swaps" class="nav-link" data-scroll-target="#other-types-of-swaps"><span class="header-section-number">4.8</span> Other Types of Swaps</a></li>
  <li><a href="#practice-questions-and-problems" id="toc-practice-questions-and-problems" class="nav-link" data-scroll-target="#practice-questions-and-problems"><span class="header-section-number">4.9</span> Practice Questions and Problems</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Swaps</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
References
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>HULL, John. Options, futures, and other derivatives. Ninth edition. Harlow: Pearson, 2018. ISBN 978-1-292-21289-0.
<ul>
<li>Chapter 7 - Swaps</li>
</ul></li>
<li>PIRIE, Wendy L. Derivatives. Hoboken: Wiley, 2017. CFA institute investment series. ISBN 978-1-119-38181-5.
<ul>
<li>Chapter 2 - Basics of Derivative Pricing and Valuation</li>
<li>Chapter 3 - Pricing and Valuation of Forward Commitments</li>
</ul></li>
</ul>
</div>
</div>
<p><strong>Learning Outcomes:</strong></p>
<ul>
<li>Understand the fundamental principles and nature of swaps, including their purpose and functionality in financial markets.</li>
<li>Analyze the mechanics and applications of interest rate swaps, identifying the roles of comparative advantage and valuation methods.</li>
<li>Explore currency swaps, including their types, uses, and the valuation process for fixed-for-fixed currency swaps.</li>
<li>Examine additional swap arrangements outside of interest rate and currency swaps, recognizing their unique features and applications.</li>
</ul>
<section id="nature-of-swaps" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="nature-of-swaps"><span class="header-section-number">4.1</span> Nature of Swaps</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definiton
</div>
</div>
<div class="callout-body-container callout-body">
<p>A swap is an over-the-counter (OTC) contract where two parties agree to exchange cash flows at specified intervals based on predetermined terms. Due to its bilateral nature and customization, it carries default risk.</p>
</div>
</div>
<ul>
<li><p><strong>Comparison with Forward Contracts</strong>: While forward contracts involve a single cash flow exchange at a future date, swaps facilitate multiple exchanges over time, making them more flexible and useful for various financial strategies.</p></li>
<li><p><strong>Conceptual View</strong>: A swap can be seen as a series of bundled forward contracts. This perspective highlights its role in hedging and financing, where cash flow timing and valuation are crucial.</p></li>
<li><p><strong>Initial Market Value</strong>: At inception, a swap has a market value of zero, reflecting a balanced structure where some forward components may hold positive value while others hold negative value. Over time, market fluctuations and underlying asset performance alter the swap’s value.</p></li>
</ul>
</section>
<section id="interest-rate-swaps" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="interest-rate-swaps"><span class="header-section-number">4.2</span> Interest Rate Swaps</h2>
<p>This section explores a <strong>Plain Vanilla Interest Rate Swap</strong>, using a transaction between <strong>Apple and Citigroup</strong> as an example. The swap spans three years and demonstrates the core mechanics of interest rate swaps.</p>
<ul>
<li><p>Apple agrees to pay Citigroup a <strong>fixed 3% annual interest rate</strong>, with quarterly payments based on a <strong>notional principal of $100 million</strong>.</p></li>
<li><p>In return, Citigroup pays Apple interest at the <strong>three-month LIBOR rate</strong>, calculated on the same principal.</p></li>
<li><p>Apple is the fixed-rate payer, while Citigroup is the floating-rate payer.</p></li>
</ul>
<br>
<center>
<img src="images/05-2-apple-citi-1.png" width="600px">
</center>
<p><br></p>
<p>The table below illustrates potential cash flow outcomes, maintaining the <strong>$100 million notional principal</strong>. The net cash flow for Apple varies due to LIBOR fluctuations, sometimes resulting in payments and other times in receipts.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 12%">
<col style="width: 32%">
<col style="width: 26%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th>Date</th>
<th>SOFR Rate (%)</th>
<th>Floating Cash Flow Received ($’000s)</th>
<th>Fixed Cash Flow Paid ($’000s)</th>
<th>Net Cash Flow ($’000s)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>June 8, 2022</td>
<td>2.20</td>
<td>550</td>
<td>750</td>
<td>-200</td>
</tr>
<tr class="even">
<td>Sept.&nbsp;8, 2022</td>
<td>2.60</td>
<td>650</td>
<td>750</td>
<td>-100</td>
</tr>
<tr class="odd">
<td>Dec.&nbsp;8, 2022</td>
<td>2.80</td>
<td>700</td>
<td>750</td>
<td>-50</td>
</tr>
<tr class="even">
<td>Mar.&nbsp;8, 2023</td>
<td>3.10</td>
<td>775</td>
<td>750</td>
<td>+25</td>
</tr>
<tr class="odd">
<td>June 8, 2023</td>
<td>3.30</td>
<td>825</td>
<td>750</td>
<td>+75</td>
</tr>
<tr class="even">
<td>Sept.&nbsp;8, 2023</td>
<td>3.40</td>
<td>850</td>
<td>750</td>
<td>+100</td>
</tr>
<tr class="odd">
<td>Dec.&nbsp;8, 2023</td>
<td>3.60</td>
<td>900</td>
<td>750</td>
<td>+150</td>
</tr>
<tr class="even">
<td>Mar.&nbsp;8, 2024</td>
<td>3.80</td>
<td>950</td>
<td>750</td>
<td>+200</td>
</tr>
</tbody>
</table>
<section id="typical-applications-of-interest-rate-swaps" class="level3">
<h3 class="anchored" data-anchor-id="typical-applications-of-interest-rate-swaps">Typical Applications of Interest Rate Swaps</h3>
<p>Interest rate swaps are widely used for managing interest rate risk, allowing firms to <strong>adjust their exposure</strong> by switching between fixed and floating rates based on financial strategy and market outlook.</p>
<ul>
<li>Apple Converts a Floating-Rate Liability to Fixed:</li>
</ul>
<br>
<center>
<img src="images/05-3-apple-citi-2.png" width="600px">
</center>
<p><br></p>
<ul>
<li>Intel Converts a Fixed-Rate Liability to Floating:</li>
</ul>
<br>
<center>
<img src="images/05-5-intel-citi-2.png" width="600px">
</center>
<p><br></p>
<ul>
<li>Apple Converts a Fixed-Rate Asset to Floating:</li>
</ul>
<br>
<center>
<img src="images/05-6-apple-citi-3.png" width="600px">
</center>
<p><br></p>
<ul>
<li>Intel Converts a Floating-Rate Asset to Fixed:</li>
</ul>
<br>
<center>
<img src="images/05-7-intel-citi-3.png" width="600px">
</center>
<p><br></p>
</section>
</section>
<section id="the-comparative-advantage-argument" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="the-comparative-advantage-argument"><span class="header-section-number">4.3</span> The Comparative-Advantage Argument</h2>
<p>The <strong>comparative-advantage argument</strong> explains why companies engage in interest rate swaps to <strong>optimize borrowing costs</strong>. It highlights how firms can <strong>leverage differences in borrowing rates</strong> to achieve more favorable financing conditions.</p>
<section id="case-study-aaacorp-and-bbbcorp" class="level3">
<h3 class="anchored" data-anchor-id="case-study-aaacorp-and-bbbcorp">Case Study: AAACorp and BBBCorp</h3>
<p>Consider two hypothetical companies:</p>
<ul>
<li><strong>AAACorp</strong> prefers <strong>floating-rate borrowing</strong>.<br>
</li>
<li><strong>BBBCorp</strong> prefers <strong>fixed-rate borrowing</strong>.</li>
</ul>
<p>Their respective borrowing costs are:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Entity</th>
<th style="text-align: center;">Fixed Rate</th>
<th style="text-align: center;">Floating Rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">AAACorp</td>
<td style="text-align: center;">4.0%</td>
<td style="text-align: center;">Floating - 0.1%</td>
</tr>
<tr class="even">
<td style="text-align: center;">BBBCorp</td>
<td style="text-align: center;">5.2%</td>
<td style="text-align: center;">Floating + 0.6%</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>Direct Swap Mechanism:</strong> AAACorp borrows at its preferred floating rate, while BBBCorp borrows at its preferred fixed rate. They swap obligations, effectively allowing each company to access the preferred rate indirectly.</li>
</ul>
<br>
<center>
<img src="images/05-10-swap-directly.png" width="600px">
</center>
<p><br></p>
<ul>
<li><strong>Indirect Swap via a Financial Institution:</strong> A financial institution can act as an intermediary, structuring the swap between AAACorp and BBBCorp. This setup reduces negotiation complexities and often enhances efficiency.</li>
</ul>
<br>
<center>
<img src="images/05-11-swap-indirectly.png" width="600px">
</center>
<p><br></p>
</section>
<section id="criticism-of-the-comparative-advantage-argument" class="level3">
<h3 class="anchored" data-anchor-id="criticism-of-the-comparative-advantage-argument">Criticism of the Comparative-Advantage Argument</h3>
<p>While this argument supports the rationale for interest rate swaps, it has limitations:</p>
<p><strong>Mismatch in Rate Terms:</strong></p>
<ul>
<li>Fixed rates (e.g., 4.0% for AAACorp and 5.2% for BBBCorp) apply to <strong>5-year loans</strong>.<br>
</li>
<li>Floating rates (e.g., Floating - 0.1% for AAACorp and Floating + 0.6% for BBBCorp) are based on <strong>6-month terms</strong>.<br>
</li>
<li>This disparity complicates direct comparisons of borrowing advantages.</li>
</ul>
<p><strong>Future Rate Uncertainty:</strong></p>
<ul>
<li>BBBCorp’s <strong>future borrowing costs</strong> depend on the spread over the floating rate at each reset.<br>
</li>
<li>If interest rates <strong>fluctuate significantly</strong>, BBBCorp may face unexpected financial exposure.</li>
</ul>
</section>
</section>
<section id="valuation-of-interest-rate-swaps" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="valuation-of-interest-rate-swaps"><span class="header-section-number">4.4</span> Valuation of Interest Rate Swaps</h2>
<p>Interest rate swaps are used to manage interest rate exposure, and their value fluctuates as market conditions change. At inception, a swap’s value is <strong>approximately zero</strong>, reflecting an initial balance between fixed and floating cash flows. Over time, valuation techniques—particularly those using <strong>Forward Rate Agreements (FRAs)</strong>—help determine its market value.</p>
<section id="valuation-framework" class="level3">
<h3 class="anchored" data-anchor-id="valuation-framework">Valuation Framework</h3>
<p>The swap valuation process consists of three key steps:</p>
<ol type="1">
<li><p><strong>Calculate Floating Forward Rates:</strong> Use market data to estimate future floating interest rates, which determine floating-rate payments.</p></li>
<li><p><strong>Determine Swap Cash Flows:</strong> Apply calculated forward rates to estimate future cash flows for both fixed and floating legs of the swap.</p></li>
<li><p><strong>Discount Cash Flows to Present Value:</strong> Discount future cash flows using Overnight Indexed Swap (OIS) rates, adjusting for time value and credit risk.</p></li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<strong>Example: Swap Valuation</strong>
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<section id="swap-agreement-overview" class="level3">
<h3 class="anchored" data-anchor-id="swap-agreement-overview">Swap Agreement Overview</h3>
<ul>
<li><strong>Structure</strong>: A swap where one party pays a fixed annual rate of 3% and receives SOFR semi-annually on a $100 million principal.<br>
</li>
<li><strong>Remaining Term</strong>: 1.2 years, with cash flow exchanges at 0.2, 0.7, and 1.2 years.<br>
</li>
<li><strong>Risk-Free Rates</strong> (OIS zero rates for different maturities):
<ul>
<li>3 months: 2.8%<br>
</li>
<li>9 months: 3.2%<br>
</li>
<li>15 months: 3.4%<br>
</li>
</ul></li>
<li><strong>Historical SOFR Rate</strong>: 2.9% (already fixed for the upcoming 3-month exchange).<br>
</li>
<li><strong>Projected Forward SOFR Rates</strong>:</li>
</ul>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Time (years)</th>
<th style="text-align: center;">Continuous Compounding</th>
<th style="text-align: center;">Semi-Annual Compounding</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0.2</td>
<td style="text-align: center;">2.50%</td>
<td style="text-align: center;">2.516%</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.7</td>
<td style="text-align: center;">3.36%</td>
<td style="text-align: center;">3.388%</td>
</tr>
<tr class="odd">
<td style="text-align: center;">1.2</td>
<td style="text-align: center;">3.68%</td>
<td style="text-align: center;">3.714%</td>
</tr>
</tbody>
</table>
</section>
<section id="cash-flow-valuation" class="level3">
<h3 class="anchored" data-anchor-id="cash-flow-valuation">Cash Flow Valuation</h3>
<p>The table below details the swap’s fixed and floating cash flows, their net impact, and their <strong>present value</strong> after discounting.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 18%">
<col style="width: 21%">
<col style="width: 16%">
<col style="width: 14%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Time (years)</th>
<th style="text-align: center;">Fixed Cash Flow ($M)</th>
<th style="text-align: center;">Floating Cash Flow ($M)</th>
<th style="text-align: center;">Net Cash Flow ($M)</th>
<th style="text-align: center;">Discount Factor</th>
<th style="text-align: center;">Present Value ($M)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0.2</td>
<td style="text-align: center;">-1.500</td>
<td style="text-align: center;">+1.258</td>
<td style="text-align: center;">-0.242</td>
<td style="text-align: center;">0.9944</td>
<td style="text-align: center;">-0.241</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.7</td>
<td style="text-align: center;">-1.500</td>
<td style="text-align: center;">+1.694</td>
<td style="text-align: center;">+0.194</td>
<td style="text-align: center;">0.9778</td>
<td style="text-align: center;">+0.190</td>
</tr>
<tr class="odd">
<td style="text-align: center;">1.2</td>
<td style="text-align: center;">-1.500</td>
<td style="text-align: center;">+1.857</td>
<td style="text-align: center;">+0.357</td>
<td style="text-align: center;">0.9600</td>
<td style="text-align: center;">+0.343</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>Total</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>+0.292</strong></td>
</tr>
</tbody>
</table>
<ul>
<li><p><strong>Fixed Cash Flow</strong> (at 0.7 years):<br>
<span class="math display">\[
0.5 \times 0.03 \times 100 = -1.5 \text{ million}
\]</span></p></li>
<li><p><strong>Floating Cash Flow</strong> (based on 3.388% semi-annual rate for 0.7 years):<br>
<span class="math display">\[
0.5 \times 0.03388 \times 100 = 1.694 \text{ million}
\]</span></p></li>
<li><p><strong>Present Value of Net Cash Flow</strong> (discounting at OIS rate for 0.7 years):<br>
<span class="math display">\[
0.194 \times e^{-0.032 \times 0.7} = 0.190 \text{ million}
\]</span></p></li>
<li><p><strong>Final Swap Value</strong>:<br>
The sum of all present values across time points, resulting in a swap valuation of <strong>$0.292 million</strong>.</p></li>
<li><p>This valuation assumes <strong>simplifications</strong> (e.g., ignoring holiday calendars and day count conventions), which may affect precise cash flows.<br>
</p></li>
</ul>
</section>
</div>
</div>
</div>
</section>
</section>
<section id="currency-swaps" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="currency-swaps"><span class="header-section-number">4.5</span> Currency Swaps</h2>
<p>Currency swaps are financial instruments that enable <strong>the exchange of principal and interest payments in different currencies</strong> between two parties. These contracts help firms manage currency exposure, reduce borrowing costs, and optimize investments across global markets.</p>
<p>In a <strong>fixed-for-fixed currency swap</strong>, parties exchange fixed interest rate payments in one currency for fixed payments in another currency, along with the principal exchange at the start and end of the contract.</p>
<p>Currency swaps are widely used for:</p>
<ol type="1">
<li><p><strong>Liability Management:</strong> Firms <strong>convert liabilities</strong> from one currency to another to match their currency exposure and reduce exchange rate risk.</p></li>
<li><p><strong>Investment Optimization:</strong> Investors <strong>swap investment returns</strong> between currencies to access favorable interest rates or hedge against currency fluctuations.</p></li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Case Study: British Petroleum and Barclays Swap Agreement
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<section id="agreement-overview" class="level4">
<h4 class="anchored" data-anchor-id="agreement-overview">Agreement Overview</h4>
<ul>
<li><strong>Parties Involved</strong>: British Petroleum and Barclays.<br>
</li>
<li><strong>Term</strong>: 5 years.<br>
</li>
<li><strong>Structure</strong>:
<ul>
<li>British Petroleum pays a fixed 3% interest rate in USD.<br>
</li>
<li>British Petroleum receives a fixed 4% interest rate in GBP.<br>
</li>
</ul></li>
<li><strong>Principal Exchange</strong>:
<ul>
<li>USD 15 million exchanged for GBP 10 million at inception.<br>
</li>
<li>Principal amounts are re-exchanged at the end of the swap.<br>
</li>
</ul></li>
<li><strong>Interest Payments</strong>: Made annually, based on the fixed rates in each currency.</li>
</ul>
</section>
<section id="yearly-cash-flow-summary" class="level4">
<h4 class="anchored" data-anchor-id="yearly-cash-flow-summary">Yearly Cash Flow Summary</h4>
<p>The table below illustrates the cash flows for British Petroleum exchanged over the swap’s duration:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 37%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Date</th>
<th style="text-align: center;">USD Cash Flow (millions)</th>
<th style="text-align: center;">GBP Cash Flow (millions)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Feb 1, 2022</td>
<td style="text-align: center;">+15.00</td>
<td style="text-align: center;">-10.00</td>
</tr>
<tr class="even">
<td style="text-align: center;">Feb 1, 2023</td>
<td style="text-align: center;">-0.45</td>
<td style="text-align: center;">+0.40</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Feb 1, 2024</td>
<td style="text-align: center;">-0.45</td>
<td style="text-align: center;">+0.40</td>
</tr>
<tr class="even">
<td style="text-align: center;">Feb 1, 2025</td>
<td style="text-align: center;">-0.45</td>
<td style="text-align: center;">+0.40</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Feb 1, 2026</td>
<td style="text-align: center;">-0.45</td>
<td style="text-align: center;">+0.40</td>
</tr>
<tr class="even">
<td style="text-align: center;">Feb 1, 2027</td>
<td style="text-align: center;">-15.45</td>
<td style="text-align: center;">+10.40</td>
</tr>
</tbody>
</table>
</section>
</div>
</div>
</div>
<section id="comparative-advantage-in-currency-swaps" class="level3">
<h3 class="anchored" data-anchor-id="comparative-advantage-in-currency-swaps">Comparative Advantage in Currency Swaps</h3>
<p>A <strong>comparative advantage</strong> in currency swaps arises when companies face different borrowing costs in various currencies due to <strong>taxation, credit ratings, or market conditions</strong>.</p>
<ul>
<li><strong>Efficiency</strong>: Currency swaps enable companies to <strong>lower borrowing costs</strong> and manage currency risk.<br>
</li>
<li><strong>Strategic Use</strong>: They help <strong>convert liabilities and investments</strong> across different currencies.<br>
</li>
<li><strong>Comparative Advantage</strong>: Firms leverage <strong>differential borrowing costs</strong> to gain financial benefits.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Case Study: General Electric &amp; Qantas Airways
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li><strong>Scenario</strong>:
<ul>
<li>General Electric (GE) wants to borrow in Australian dollars (AUD).<br>
</li>
<li>Qantas Airways wants to borrow in U.S. dollars (USD).</li>
</ul></li>
<li><strong>Borrowing Costs (after tax adjustments)</strong>:</li>
</ul>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;"></th>
<th style="text-align: center;">USD</th>
<th style="text-align: center;">AUD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">General Electric</td>
<td style="text-align: center;">5.0%</td>
<td style="text-align: center;">7.6%</td>
</tr>
<tr class="even">
<td style="text-align: center;">Qantas Airways</td>
<td style="text-align: center;">7.0%</td>
<td style="text-align: center;">8.0%</td>
</tr>
</tbody>
</table>
<p>Since <strong>General Electric has a lower borrowing cost in USD</strong> and <strong>Qantas Airways has a lower borrowing cost in AUD</strong>, they can <strong>swap their borrowing obligations</strong> to access cheaper rates than they would get individually.</p>
<br>
<center>
<img src="images/05-17-currency-swap.png" width="600px">
</center>
<p><br></p>
</div>
</div>
</div>
</section>
</section>
<section id="valuation-of-fixed-for-fixed-currency-swaps" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="valuation-of-fixed-for-fixed-currency-swaps"><span class="header-section-number">4.6</span> Valuation of Fixed-for-Fixed Currency Swaps</h2>
<p>Fixed-for-fixed currency swaps involve <strong>exchanging fixed interest payments in two different currencies</strong> over a set period, alongside an initial and final principal exchange. These swaps can be viewed as <strong>a series of forward foreign exchange contracts</strong>, where future exchange rates determine the valuation of expected cash flows.</p>
<p>The core assumption in valuing these swaps is that <strong>forward exchange rates reflect the market’s expectations of future currency values</strong>. The valuation process, therefore, involves discounting cash flows in each currency and converting them using forward exchange rates.</p>
<ul>
<li><strong>Forward Exchange Rates Matter</strong>: The swap’s valuation depends on market expectations of future exchange rates.<br>
</li>
<li><strong>Discounting Reflects Present Value</strong>: Future cash flows must be discounted using the domestic interest rate to obtain today’s value.<br>
</li>
<li><strong>Principal Exchange is Crucial</strong>: The final principal repayment significantly impacts the swap’s overall valuation.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<strong>Example: Valuation of a Currency Swap</strong>
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Consider a <strong>U.S. dollar (USD) - Japanese yen (JPY) swap</strong> with the following terms:</p>
<ul>
<li><strong>Fixed Interest Rates</strong>:
<ul>
<li>USD: 2.5% per annum (continuous compounding).<br>
</li>
<li>JPY: 1.5% per annum (continuous compounding).<br>
</li>
</ul></li>
<li><strong>Swap Payments</strong>:
<ul>
<li>Receives 3% interest in JPY.<br>
</li>
<li>Pays 4% interest in USD.<br>
</li>
</ul></li>
<li><strong>Principal Exchange</strong>:
<ul>
<li>USD 10 million exchanged for 1,200 million JPY at inception and at maturity.<br>
</li>
</ul></li>
<li><strong>Remaining Swap Duration</strong>: 3 years.<br>
</li>
<li><strong>Current Spot Exchange Rate</strong>: 110 JPY per USD.</li>
</ul>
<p>The table below outlines the <strong>expected cash flows</strong> in both currencies, their conversion using forward exchange rates, and their <strong>discounted present values</strong>:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 15%">
<col style="width: 13%">
<col style="width: 12%">
<col style="width: 22%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Time (years)</th>
<th style="text-align: center;">Dollar Cash Flow (million)</th>
<th style="text-align: center;">Yen Cash Flow (million)</th>
<th style="text-align: center;">Forward Exchange Rate</th>
<th style="text-align: center;">Dollar Value of Yen Cash Flow (million)</th>
<th style="text-align: center;">Net Cash Flow (million)</th>
<th style="text-align: center;">Present Value (million)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">-0.4</td>
<td style="text-align: center;">+36</td>
<td style="text-align: center;">0.009182</td>
<td style="text-align: center;">0.3306</td>
<td style="text-align: center;">-0.0694</td>
<td style="text-align: center;">-0.0677</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">-0.4</td>
<td style="text-align: center;">+36</td>
<td style="text-align: center;">0.009275</td>
<td style="text-align: center;">0.3339</td>
<td style="text-align: center;">-0.0661</td>
<td style="text-align: center;">-0.0629</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">-10.4</td>
<td style="text-align: center;">+1236</td>
<td style="text-align: center;">0.009368</td>
<td style="text-align: center;">11.5786</td>
<td style="text-align: center;">+1.1786</td>
<td style="text-align: center;">+1.0934</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>Total</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>+0.9629</strong></td>
</tr>
</tbody>
</table>
<ul>
<li><p><strong>USD Payment:</strong><br>
<span class="math display">\[
0.04 \times 10 = -0.4 \text{ million USD per year}
\]</span></p></li>
<li><p><strong>JPY Receipt:</strong><br>
<span class="math display">\[
1,200 \times 0.03 = +36 \text{ million JPY per year}
\]</span></p></li>
<li><p><strong>Principal Exchange at Maturity (Year 3):</strong></p>
<ul>
<li>Pays: USD 10 million<br>
</li>
<li>Receives: 1,200 million JPY</li>
</ul></li>
</ul>
<section id="forward-exchange-rate-calculations" class="level4">
<h4 class="anchored" data-anchor-id="forward-exchange-rate-calculations">Forward Exchange Rate Calculations</h4>
<p>The valuation <strong>relies on forward exchange rates</strong>, derived from the interest rate differential between USD and JPY:</p>
<p><span class="math display">\[
F_t = S_0 \times e^{(r - r_f) \times t}
\]</span></p>
<ul>
<li><span class="math inline">\(S_0 = 0.009091\)</span> (initial spot rate, 1/110 JPY per USD).<br>
</li>
<li><span class="math inline">\(r = 2.5\%\)</span> (USD interest rate).<br>
</li>
<li><span class="math inline">\(r_f = 1.5\%\)</span> (JPY interest rate).<br>
</li>
<li><span class="math inline">\(t\)</span> = time in years.</li>
</ul>
</section>
<section id="forward-rates-for-each-year" class="level4">
<h4 class="anchored" data-anchor-id="forward-rates-for-each-year">Forward Rates for Each Year</h4>
<ul>
<li><strong>Year 1</strong>:<br>
<span class="math display">\[
0.009091 \times e^{(0.025 - 0.015) \times 1} = 0.009182
\]</span></li>
<li><strong>Year 2</strong>:<br>
<span class="math display">\[
0.009091 \times e^{(0.025 - 0.015) \times 2} = 0.009275
\]</span></li>
<li><strong>Year 3</strong>:<br>
<span class="math display">\[
0.009091 \times e^{(0.025 - 0.015) \times 3} = 0.009368
\]</span></li>
</ul>
</section>
<section id="valuation-process" class="level4">
<h4 class="anchored" data-anchor-id="valuation-process">Valuation Process</h4>
<ol type="1">
<li><strong>Convert Future JPY Cash Flows to USD Using Forward Rates</strong>
<ul>
<li>Example (Year 1):<br>
<span class="math display">\[
36 \times 0.009182 = 0.3306 \text{ million USD}
\]</span></li>
<li><strong>Net Cash Flow</strong> (Year 1):<br>
<span class="math display">\[
0.3306 - 0.4 = -0.0694 \text{ million USD}
\]</span></li>
</ul></li>
<li><strong>Discount Net Cash Flows Using USD Interest Rate (2.5%)</strong>
<ul>
<li>Example (Year 1):<br>
<span class="math display">\[
-0.0694 \times e^{-0.025 \times 1} = -0.0677 \text{ million USD}
\]</span></li>
</ul></li>
<li><strong>Repeat for Years 2 and 3</strong>
<ul>
<li>The same process applies for each year’s cash flows, using the respective forward rates and discount factors.</li>
</ul></li>
<li><strong>Sum Present Values to Obtain Swap Valuation</strong>
<ul>
<li>The total present value of net cash flows is $0.9629 million USD, representing the swap’s market value.</li>
</ul></li>
</ol>
</section>
</div>
</div>
</div>
</section>
<section id="other-currency-swaps" class="level2" data-number="4.7">
<h2 data-number="4.7" class="anchored" data-anchor-id="other-currency-swaps"><span class="header-section-number">4.7</span> Other Currency Swaps</h2>
<section id="fixed-for-floating-currency-swaps" class="level3">
<h3 class="anchored" data-anchor-id="fixed-for-floating-currency-swaps">Fixed-for-Floating Currency Swaps</h3>
<p>A fixed-for-floating currency swap combines elements of <strong>a fixed-for-fixed currency swap and a fixed-for-floating interest rate swap</strong>. In this arrangement, one party pays a fixed interest rate in one currency while receiving a floating interest rate in another currency.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Consider a swap agreement where:</p>
<ul>
<li>A party pays a floating interest rate on GBP 7 million.<br>
</li>
<li>The same party receives a fixed 3% interest rate on USD 10 million, with semiannual payments over 10 years.</li>
</ul>
<p>This swap can be broken down into two components:</p>
<ol type="1">
<li><strong>Currency Swap Component</strong>:
<ul>
<li><strong>Receives</strong> 3% fixed interest on USD 10 million.<br>
</li>
<li><strong>Pays</strong> 4% fixed interest on GBP 7 million.</li>
</ul></li>
<li><strong>Interest Rate Swap Component</strong>:
<ul>
<li><strong>Receives</strong> 4% fixed interest.<br>
</li>
<li><strong>Pays</strong> floating sterling interest on GBP 7 million.<br>
</li>
</ul></li>
</ol>
</div>
</div>
</div>
</section>
<section id="floating-for-floating-currency-swaps" class="level3">
<h3 class="anchored" data-anchor-id="floating-for-floating-currency-swaps">Floating-for-Floating Currency Swaps</h3>
<p>A floating-for-floating currency swap involves exchanging <strong>floating interest payments in two different currencies</strong>. It effectively combines a fixed-for-fixed currency swap with two floating interest rate swaps.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A party exchanges:</p>
<ul>
<li>Sterling floating interest payments on GBP 7 million.</li>
<li>For dollar floating interest payments on USD 10 million.</li>
</ul>
<p>This structure consists of:</p>
<ol type="1">
<li><strong>Base Swap</strong>:
<ul>
<li><strong>Pays</strong> 3% fixed interest on USD 10 million.<br>
</li>
<li><strong>Receives</strong> 4% fixed interest on GBP 7 million.</li>
</ul></li>
<li><strong>Interest Rate Swap #1</strong>:
<ul>
<li><strong>Pays</strong> 4% fixed interest.<br>
</li>
<li><strong>Receives</strong> floating sterling interest on GBP 7 million.</li>
</ul></li>
<li><strong>Interest Rate Swap #2</strong>:
<ul>
<li><strong>Pays</strong> 3% fixed interest.<br>
</li>
<li><strong>Receives</strong> floating USD interest on USD 10 million.<br>
</li>
</ul></li>
</ol>
</div>
</div>
</div>
</section>
</section>
<section id="other-types-of-swaps" class="level2" data-number="4.8">
<h2 data-number="4.8" class="anchored" data-anchor-id="other-types-of-swaps"><span class="header-section-number">4.8</span> Other Types of Swaps</h2>
<p>Beyond currency and interest rate swaps, financial markets offer specialized swaps tailored for <strong>risk management, investment strategies, and arbitrage opportunities</strong>.</p>
<ul>
<li><p><strong>Amortizing/Step-Up Swap</strong>: The notional principal gradually increases or decreases to match an underlying asset or liability.</p></li>
<li><p><strong>Compounding Swap</strong>: Interest payments are reinvested, compounding over the swap’s duration.</p></li>
<li><p><strong>Constant Maturity Swap (CMS)</strong>: The interest rate resets periodically based on the rate of a constant maturity instrument (e.g., a 10-year Treasury note).</p></li>
<li><p><strong>LIBOR-in-Arrears Swap</strong>: The interest rate is determined at the end of the payment period instead of the beginning, increasing uncertainty.</p></li>
<li><p><strong>Accrual Swap</strong>: Interest accrues only when a benchmark rate (or index) meets specific conditions.</p></li>
<li><p><strong>Equity Swap</strong>: Exchanges equity returns (e.g., stock performance) for either fixed or floating interest payments.</p></li>
<li><p><strong>Cross-Currency Interest Rate Swap</strong>: A variation of currency swaps where one or both legs involve floating rates in different currencies.</p></li>
<li><p><strong>Diff Swap</strong>: An interest rate differential swap, where payments depend on the difference between two reference rates.</p></li>
<li><p><strong>Commodity Swap</strong>: One party pays a fixed price for a commodity, while the other pays the floating market price over time.</p></li>
<li><p><strong>Variance Swap</strong>: A contract based on future volatility, where payments depend on the variance of an underlying asset’s price.</p></li>
</ul>
</section>
<section id="practice-questions-and-problems" class="level2" data-number="4.9">
<h2 data-number="4.9" class="anchored" data-anchor-id="practice-questions-and-problems"><span class="header-section-number">4.9</span> Practice Questions and Problems</h2>
<ol type="1">
<li><p>A bank finds that its assets are not matched with its liabilities. It is taking floating-rate deposits and making fixed-rate loans. How can swaps be used to offset the risk?</p></li>
<li><p>Explain the difference between the credit risk and the market risk in a financial contract.</p></li>
<li><p>Explain why a bank is subject to credit risk when it enters into two offsetting swap contracts.</p></li>
<li><p>Why is the expected loss from a default on a swap less than the expected loss from the default on a loan to the same counterparty with the same principal?</p></li>
<li><p>A corporate treasurer tells you that he has just negotiated a five-year loan at a competitive fixed rate of interest of 5.2%. The treasurer explains that he achieved the 5.2% rate by borrowing at six-month LIBOR plus 150 basis points and swapping LIBOR for 3.7%. He goes on to say that this was possible because his company has a comparative advantage in the floating-rate market. What has the treasurer overlooked?</p></li>
<li><p>Companies A and B have been offered the following rates per annum on a $20 million five-year loan:</p></li>
</ol>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;"></th>
<th style="text-align: center;">Fixed Rate</th>
<th style="text-align: center;">Floating Rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Company A</td>
<td style="text-align: center;">5.0%</td>
<td style="text-align: center;">Floating + 0.1%</td>
</tr>
<tr class="even">
<td style="text-align: center;">Company B</td>
<td style="text-align: center;">6.4%</td>
<td style="text-align: center;">Floating + 0.6%</td>
</tr>
</tbody>
</table>
<p>Company A requires a floating-rate loan; company B requires a fixed-rate loan. Design a swap that will net a bank, acting as intermediary, 0.1% per annum and that will appear equally attractive to both companies.</p>
<ol start="7" type="1">
<li>Company X wishes to borrow U.S. dollars at a fixed rate of interest. Company Y wishes to borrow Japanese yen at a fixed rate of interest. The amounts required by the two companies are roughly the same at the current exchange rate. The companies have been quoted the following interest rates, which have been adjusted for the impact of taxes:</li>
</ol>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;"></th>
<th style="text-align: center;">Yen</th>
<th style="text-align: center;">Dollars</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Company X</td>
<td style="text-align: center;">5.0%</td>
<td style="text-align: center;">9.6%</td>
</tr>
<tr class="even">
<td style="text-align: center;">Company Y</td>
<td style="text-align: center;">6.5%</td>
<td style="text-align: center;">10.0%</td>
</tr>
</tbody>
</table>
<p>Design a swap that will net a bank, acting as intermediary, 50 basis points per annum. Make the swap equally attractive to the two companies and ensure that all foreign exchange risk is assumed by the bank.</p>
<ol start="8" type="1">
<li>Companies X and Y have been offered the following rates per annum on a $5 million 10-year investment:</li>
</ol>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;"></th>
<th style="text-align: center;">Fixed Rate</th>
<th style="text-align: center;">Floating Rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Company X</td>
<td style="text-align: center;">8.0%</td>
<td style="text-align: center;">Floating</td>
</tr>
<tr class="even">
<td style="text-align: center;">Company Y</td>
<td style="text-align: center;">8.8%</td>
<td style="text-align: center;">Floating</td>
</tr>
</tbody>
</table>
<p>Company X requires a fixed-rate investment; company Y requires a floating-rate investment. Design a swap that will net a bank, acting as intermediary, 0.2% per annum and will appear equally attractive to X and Y.</p>
<ol start="9" type="1">
<li><p>A $100 million interest rate swap has a remaining life of 10 months. Under the terms of the swap, six-month LIBOR is exchanged for 7% per annum (compounded semiannually). The average of the bid-offer rate being exchanged for six-month LIBOR in swaps of all maturities is currently 5% per annum with continuous compounding (5.063% with semi-annual compounding). The six-month LIBOR rate was 4.6% per annum two months ago. What is the current value of the swap to the party paying floating? What is its value to the party paying fixed?</p></li>
<li><p>A currency swap has a remaining life of 15 months. It involves exchanging interest at 10% on 20 million GBP for interest at 6% on 30 million USD once a year. The term structure of interest rates in both the United Kingdom and the United States is currently flat, and if the swap were negotiated today the interest rates exchanged would be 4% in dollars and 7% in sterling. All interest rates are quoted with annual compounding (the continuously compounded interest rates in sterling and dollars are 6.766% per annum and 3.922% per annum). The current exchange rate (dollars per pound sterling) is 1.5500. What is the value of the swap to the party paying sterling? What is the value of the swap to the party paying dollars?</p></li>
</ol>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./week_03.html" class="pagination-link" aria-label="Determination of Forward and Futures Prices">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Determination of Forward and Futures Prices</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./week_05.html" class="pagination-link" aria-label="Options">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Options</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>